apiVersion: v2
name: authelia
version: 0.1.1
kubeVersion: ">= 1.13.0"
description: Authelia Experimental Chart
type: application
keywords: []
home: https://www.authelia.com
sources:
  - https://www.github.com/authelia/chartrepo/charts/experimental/
  - https://www.github.com/authelia/authelia
dependencies: []
maintainers:
  - name: james-d-elliott
    email: james-d-elliott@users.noreply.github.com
    url: https://github.com/james-d-elliott
icon: https://avatars2.githubusercontent.com/u/59122411?s=200&v=4
appVersion: 4.25.0
deprecated: false
annotations:
  alpha: "true"
