---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authelia.name" . }}
  labels:
{{- include "authelia.labels" . | nindent 4 }}
{{- with .Values.configMap.extraLabels -}}
{{ toYaml . | nindent 4 }}
{{- end -}}
{{- if or (include "authelia.annotations" .) .Values.configMap.extraAnnotations }}
  annotations:
{{- include "authelia.annotations" . | nindent 4 }}
{{- with .Values.configMap.extraAnnotations -}}
{{ toYaml . | nindent 4 }}
{{- end -}}
{{- end }}
data:
  configuration.yml: |
    host: 0.0.0.0
    port: {{ .Values.configMap.port | default "9091" }}
    log_level: {{ .Values.configMap.log_level | default "info" }}
    default_redirection_url: {{ .Values.configMap.default_redirection_url | default (printf "https://www.%s" .Values.configMap.domain) }}
    server:
{{ toYaml .Values.configMap.server | indent 6 }}
    totp:
      issuer: {{ .Values.configMap.totp.issuer | default .Values.configMap.domain }}
      period: {{ .Values.configMap.totp.period | default "30" }}
      skew: {{ .Values.configMap.totp.skew | default "1" }}
{{- with .Values.configMap.duo_api }}
    duo_api:
{{ toYaml . | nindent 6 }}
{{- end }}
    authentication_backend:
      disable_reset_password: {{ .Values.configMap.authentication_backend.disable_reset_password }}
      ldap:
{{ toYaml .Values.configMap.authentication_backend.ldap | indent 8 }}
    session:
      name: {{ .Values.configMap.session.name | default "authelia_session" }}
      domain: {{ .Values.configMap.domain }}
      expiration: {{ .Values.configMap.session.expiration | default "1M" }}
      inactivity: {{ .Values.configMap.session.inactivity | default "5m" }}
      remember_me_duration: {{ .Values.configMap.session.remember_me_duration | default "1M" }}
{{- with .Values.configMap.session.redis }}
      redis:
{{ toYaml . | indent 8 }}
{{- end }}
    regulation:
{{ toYaml .Values.configMap.regulation | indent 6 }}
    storage:
{{- with .Values.configMap.storage.mysql }}
      mysql:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.configMap.storage.postgres }}
      postgres:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.configMap.notifier.smtp }}
    notifier:
      smtp:
{{ toYaml . | indent 8 }}
{{- end }}
    access_control:
{{ toYaml .Values.configMap.access_control | indent 6 }}
