---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authelia.name" . }}
  labels:
{{- include "authelia.labels" . | nindent 4 }}
{{- with .Values.configMap.extraLabels -}}
{{ toYaml . | nindent 4 }}
{{- end -}}
{{- if or (include "authelia.annotations" .) .Values.configMap.extraAnnotations }}
  annotations:
{{- include "authelia.annotations" . | nindent 4 }}
{{- with .Values.configMap.extraAnnotations -}}
{{ toYaml . | nindent 4 }}
{{- end -}}
{{- end }}
data:
  configuration.yml: |
    host: 0.0.0.0
    port: {{ default 9091 .Values.configMap.port }}
    log_level: {{ default "info" .Values.configMap.log_level  }}
    default_redirection_url: {{ default (printf "https://www.%s" .Values.configMap.domain) .Values.configMap.default_redirection_url }}
    server:
{{ toYaml .Values.configMap.server | indent 6 }}
    totp:
      issuer: {{ default .Values.configMap.domain .Values.configMap.totp.issuer }}
      period: {{ default 30 .Values.configMap.totp.period }}
      skew: {{ default 1 .Values.configMap.totp.skew }}
{{- with .Values.configMap.duo_api }}
    duo_api:
{{ toYaml . | nindent 6 }}
{{- end }}
    authentication_backend:
      disable_reset_password: {{ .Values.configMap.authentication_backend.disable_reset_password }}
      ldap:
{{ toYaml .Values.configMap.authentication_backend.ldap | indent 8 }}
    session:
      name: {{ default "authelia_session" .Values.configMap.session.name }}
      domain: {{ .Values.configMap.domain }}
      expiration: {{ default "1M" .Values.configMap.session.expiration }}
      inactivity: {{ default "5m" .Values.configMap.session.inactivity }}
      remember_me_duration: {{ default "1M" .Values.configMap.session.remember_me_duration }}
{{- with .Values.configMap.session.redis }}
      redis:
{{ toYaml . | indent 8 }}
{{- end }}
    regulation:
{{ toYaml .Values.configMap.regulation | indent 6 }}
    storage:
{{- with .Values.configMap.storage.mysql }}
      mysql:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.configMap.storage.postgres }}
      postgres:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.configMap.notifier.smtp }}
    notifier:
      disable_startup_check: {{ $.Values.configMap.notifier.disable_startup_check }}
      smtp:
{{ toYaml . | indent 8 }}
{{- end }}
    access_control:
{{ toYaml .Values.configMap.access_control | indent 6 }}
