---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authelia.name" . }}
  labels:
{{- include "authelia.labels" . | nindent 4 }}
{{- if include "authelia.annotations" . }}
annotations:
{{- include "authelia.annotations" . | nindent 4 }}
{{- end }}
data:
  configuration.yml: |
    host: 0.0.0.0
    port: {{ .Values.authelia.config.port | default "9091" }}
    log_level: {{ .Values.authelia.config.log_level | default "info" }}
    default_redirection_url: {{ .Values.authelia.config.default_redirection_url | default (printf "https://%s" .Values.authelia.config.domain) }}
    server:
{{ toYaml .Values.authelia.config.server | indent 6 }}
    totp:
      issuer: {{ .Values.authelia.config.totp.issuer | default .Values.authelia.config.domain }}
      period: {{ .Values.authelia.config.totp.period | default "30" }}
      skew: {{ .Values.authelia.config.totp.skew | default "1" }}
{{- if .Values.authelia.config.duo_api }}
    duo_api:
{{ toYaml .Values.authelia.config.duo_api | nindent 6 }}
{{- end }}
    authentication_backend:
      disable_reset_password: {{ .Values.authelia.config.authentication_backend.disable_reset_password }}
      ldap:
{{ toYaml .Values.authelia.config.authentication_backend.ldap | indent 8 }}
    session:
      name: {{ .Values.authelia.config.session.name | default "authelia_session" }}
      domain: {{ .Values.authelia.config.domain }}
      expiration: {{ .Values.authelia.config.session.expiration | default "1M" }}
      inactivity: {{ .Values.authelia.config.session.inactivity | default "5m" }}
      remember_me_duration: {{ .Values.authelia.config.session.remember_me_duration | default "1M" }}
{{- if .Values.authelia.config.session.redis }}
      redis:
{{ toYaml .Values.authelia.config.session.redis | indent 8 }}
{{- end }}
    regulation:
{{ toYaml .Values.authelia.config.regulation | indent 6 }}
    storage:
{{- if .Values.authelia.config.storage.mysql }}
      mysql:
{{ toYaml .Values.authelia.config.storage.mysql | indent 8 }}
{{- end }}
{{- if .Values.authelia.config.storage.postgres }}
      postgres:
{{ toYaml .Values.authelia.config.storage.postgres | indent 8 }}
{{- end }}
    notifier:
{{- if .Values.authelia.config.notifier.smtp }}
      smtp:
{{ toYaml .Values.authelia.config.notifier.smtp | indent 8 }}
{{- end }}
    access_control:
{{ toYaml .Values.authelia.config.access_control | indent 6 }}
