{{- if eq .Values.authelia.replicaSetType "DaemonSet" }}
---
{{- if semverCompare "^1.16-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta1
{{- end }}
kind: DaemonSet
metadata:
  name: {{ include "authelia.name" . }}
  labels:
{{- include "authelia.labels" . | nindent 4 }}
{{- if .Values.authelia.labels -}}
{{ toYaml .Values.authelia.labels | nindent 4 }}
{{- end -}}
{{- if .Values.authelia.extraLabels -}}
{{ toYaml .Values.authelia.extraLabels | nindent 4 }}
{{- end -}}
{{- if or (include "authelia.annotations" .) (.Values.authelia.extraAnnotations) }}
  annotations:
{{- include "authelia.annotations" . | nindent 4 }}
{{- if .Values.authelia.extraAnnotations -}}
{{ toYaml .Values.authelia.extraAnnotations | nindent 4 }}
{{- end -}}
{{- end }}
spec:
  selector:
    matchLabels:
{{- include "authelia.matchLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{- include "authelia.labels" . | nindent 8 }}
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
{{- if .Values.authelia.selectors.nodeName }}
      nodeName: {{ .Values.authelia.selectors.nodeName }}
{{- end }}
{{- if .Values.authelia.selectors.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.authelia.selectors.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.authelia.selectors.affinity }}
      affinity:
{{ toYaml .Values.authelia.selectors.affinity | indent 8 }}
{{- end }}
{{- if .Values.authelia.securityContext }}
      securityContext:
{{ toYaml .Values.authelia.securityContext | indent 8 }}
{{- end }}
      containers:
      - name: authelia
        image: {{ include "authelia.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.image.pullSecrets }}
        imagePullSecrets:
{{- range .Values.image.pullSecrets }}
        - name: {{ . }}
{{- end }}
{{- end }}
{{- if .Values.authelia.resources }}
        resources:
{{ toYaml .Values.authelia.resources | indent 10 }}
{{- end }}
        env:
        - name: AUTHELIA_JWT_SECRET_FILE
          value: /usr/app/secrets/JWT_TOKEN
        - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
          value: /usr/app/secrets/LDAP_PASSWORD
        - name: AUTHELIA_SESSION_SECRET_FILE
          value: /usr/app/secrets/SESSION_ENCRYPTION_KEY
{{- if .Values.authelia.config.storage.postgres }}
        - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
          value: /usr/app/secrets/STORAGE_PASSWORD
{{- end }}
{{- if .Values.authelia.config.storage.mysql }}
        - name: AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE
        - name: AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE
          value: /usr/app/secrets/STORAGE_PASSWORD
{{- end }}
{{- if .Values.authelia.secret.smtp.enabled }}
        - name: AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
          value: /usr/app/secrets/SMTP_PASSWORD
{{- end }}
{{- if and (.Values.authelia.config.session.redis) (.Values.authelia.secret.redis.enabled) }}
        - name: AUTHELIA_SESSION_REDIS_PASSWORD_FILE
          value: /usr/app/secrets/REDIS_PASSWORD
{{- end }}
{{- if .Values.authelia.config.duo_api }}
        - name: AUTHELIA_DUO_API_SECRET_KEY_FILE
          value: /usr/app/secrets/DUO_API_KEY
{{- end }}

{{- if .Values.authelia.extraEnv }}
{{ toYaml .Values.authelia.extraEnv | indent 8 }}
{{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.authelia.config.port | default "9091" }}
          protocol: TCP
{{- if .Values.authelia.probes.startup }}
        startupProbe:
          httpGet:
            path: {{ .Values.authelia.probes.path | default "/api/health" }}
            port: http
{{ toYaml .Values.authelia.probes.startup | indent 10 }}
{{- end }}
{{- if .Values.authelia.probes.liveness }}
        livenessProbe:
          httpGet:
            path: {{ .Values.authelia.probes.path | default "/api/health" }}
            port: http
{{ toYaml .Values.authelia.probes.liveness | indent 10 }}
{{- end }}
{{- if .Values.authelia.probes.readiness }}
        readinessProbe:
          httpGet:
            path: {{ .Values.authelia.probes.path | default "/api/health" }}
            port: http
{{ toYaml .Values.authelia.probes.readiness | indent 10 }}
{{- end }}
        volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
        - mountPath: /usr/app/secrets
          name: secrets
          readOnly: true

{{- if .Values.authelia.podSecurityContext }}
        securityContext:
{{ toYaml .Values.authelia.podSecurityContext | indent 10 }}
{{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "authelia.name" . }}
          items:
            - key: configuration.yml
              path: configuration.yml
      - name: secrets
        secret:
          secretName: {{ .Values.authelia.secret.existingSecretName | default (include "authelia.name" .) }}
          items:
          - key: {{ .Values.authelia.secret.jwt.key | default "JWT_TOKEN" }}
            path: JWT_TOKEN
          - key: {{ .Values.authelia.secret.ldap.key | default "LDAP_PASSWORD" }}
            path: LDAP_PASSWORD
          - key: {{ .Values.authelia.secret.session.key | default "SESSION_ENCRYPTION_KEY" }}
            path: SESSION_ENCRYPTION_KEY
          - key: {{ .Values.authelia.secret.storage.key | default "STORAGE_PASSWORD" }}
            path: STORAGE_PASSWORD
{{- if .Values.authelia.secret.smtp.enabled }}
          - key: {{ .Values.authelia.secret.smtp.key | default "SMTP_PASSWORD" }}
            path: SMTP_PASSWORD
{{- end }}
{{- if and (.Values.authelia.config.session.redis) (.Values.authelia.secret.redis.enabled) }}
          - key: {{ .Values.authelia.secret.redis.key | default "REDIS_PASSWORD" }}
            path: REDIS_PASSWORD
{{- end }}
{{- if .Values.authelia.config.duo_api }}
          - key: {{ .Values.authelia.secret.duo.key | default "DUO_API_KEY" }}
            path: DUO_API_KEY
{{- end }}


{{- end }}