{{- if (include "authelia.generateSecret" .) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "authelia.name" . }}
  labels:
  {{- include "authelia.labels" . | nindent 4 }}
  {{- if include "authelia.annotations" . }}
annotations:
  {{- include "authelia.annotations" . | nindent 4 }}
  {{- end }}
data:
  {{ .Values.authelia.secret.jwt.key }}: {{ include "authelia.jwt_token" . }}
  {{ .Values.authelia.secret.session.key }}: {{ include "authelia.session_encryption_key" . }}
  {{ .Values.authelia.secret.ldap.key }}: {{ include "authelia.ldap_password" . }}
  {{ .Values.authelia.secret.storage.key }}: {{ include "authelia.storage_password" . }}
{{- if .Values.authelia.secret.redis.enabled }}
  {{ .Values.authelia.secret.redis.key }}: {{ include "authelia.redis_password" . }}
{{- end }}
{{- if .Values.authelia.secret.smtp.enabled }}
  {{ .Values.authelia.secret.smtp.key }}: {{ include "authelia.smtp_password" . }}
{{- end }}
{{- if .Values.authelia.config.duo_api }}
  {{ .Values.authelia.secret.duo.key }}: {{ .Values.authelia.secret.duo.value | b64enc }}
{{- end }}
{{- end -}}