{{ if (include "authelia.generateSecret" .) -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "authelia.name" . }}
  labels:
{{- include "authelia.labels" . | nindent 4 }}
{{- with .Values.secret.extraLabels }}
{{- toYaml . | nindent 4 }}
{{- end }}
{{- if or (include "authelia.annotations" .) .Values.secret.extraAnnotations }}
annotations:
{{- include "authelia.annotations" . | nindent 4 }}
{{- with .Values.secret.extraAnnotations }}
{{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
data:
  {{ .Values.secret.jwt.key }}: {{ include "authelia.jwtToken" . }}
  {{ .Values.secret.session.key }}: {{ include "authelia.sessionEncryptionKey" . }}
  {{ .Values.secret.ldap.key }}: {{ include "authelia.ldapPassword" . }}
  {{ .Values.secret.storage.key }}: {{ include "authelia.storagePassword" . }}
{{- if .Values.secret.redis.enabled }}
  {{ .Values.secret.redis.key }}: {{ include "authelia.redisPassword" . }}
{{- end }}
{{- if .Values.secret.smtp.enabled }}
  {{ .Values.secret.smtp.key }}: {{ include "authelia.smtpPassword" . }}
{{- end }}
{{- if and .Values.configMap.duo_api .Values.secret.duo.value }}
  {{ .Values.secret.duo.key }}: {{ .Values.secret.duo.value | b64enc }}
{{- end }}
{{- end -}}