---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authelia.name" . }}
  labels:
{{- include "authelia.labels" . | nindent 4 }}
{{- if include "authelia.annotations" . }}
annotations:
{{- include "authelia.annotations" . | nindent 4 }}
{{- end }}
spec:
  type: ClusterIP
  selector:
{{- include "authelia.matchLabels" . | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: {{ .Values.authelia.config.port | default "9091" }}
