---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authelia.name" . }}
  labels:
{{- include "authelia.labels" . | nindent 4 }}
{{- with .Values.service.extraLabels }}
{{- toYaml . | nindent 4 }}
{{- end }}
{{- if  or (include "authelia.annotations" .) .Values.service.extraAnnotations }}
  annotations:
{{- include "authelia.annotations" . | nindent 4 }}
{{- with .Values.service.extraAnnotations }}
{{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if and .Values.service.loadBalancerIP (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end -}}
{{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
  ports:
  - name: http
    protocol: TCP
    port: {{ default 80 .Values.service.port }}
{{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
    nodePort: {{ default (default 80 .Values.service.port) .Values.service.nodePort }}
{{- end }}
    targetPort: http
  selector:
{{- include "authelia.matchLabels" . | nindent 4 }}