{{ if (include "authelia.ingress.traefikCRD.enabled" .) -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "authelia.name" . }}
  labels:
{{- include "authelia.labels" . | nindent 4 }}
{{- with .Values.ingress.extraLabels }}
{{- toYaml . | nindent 4 }}
{{- end }}
{{- if  or (include "authelia.annotations" .) .Values.ingress.extraAnnotations }}
  annotations:
{{- include "authelia.annotations" . | nindent 4 }}
{{- with .Values.ingress.extraAnnotations }}
{{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
spec:
  entryPoints:
{{- with .Values.ingress.traefikCRD.entryPoints }}
{{- toYaml . | nindent 2 }}
{{- else }}
  - http
{{- end }}
  routes:
  - kind: Rule
    match: {{ printf "Host(`%s`) && PathPrefix(`%s`)" (include "authelia.ingressHost" .) (default "/" .Values.configMap.path ) }}
    priority: {{ default 10 .Values.ingress.traefikCRD.priority }}
    middlewares:
    - name: {{ include "authelia.name" . }}
      namespace: {{ .Release.Namespace }}
    services:
    - kind: Service
      name: {{ include "authelia.name" . }}
      port: {{ default 80 .Values.service.port }}
      namespace: {{ .Release.Namespace }}
      passHostHeader: true
      strategy: {{ default "RoundRobin" .Values.ingress.traefikCRD.strategy }}
      scheme: {{ default "http" .Values.ingress.traefikCRD.scheme }}
      weight: {{ default 10 .Values.ingress.traefikCRD.weight }}
      responseForwarding:
        flushInterval: {{ default "100ms" .Values.ingress.traefikCRD.responseForwardingFlushInterval }}
{{- if .Values.ingress.traefikCRD.sticky }}
      sticky:
        cookie:
          httpOnly: true
          name: {{ default (printf "%s_traefik_lb" (include "authelia.name" .)) .Values.ingress.traefikCRD.stickyCookieNameOverride }}
          secure: true
          sameSite: None
{{- end }}
{{- if .Values.ingress.traefikCRD.tls }}
  tls:
    secretName: {{ default (printf "%s-traefik-tls" (include "authelia.name" .)) .Values.ingress.traefikCRD.tls.secretName }}
    options:
{{- if (include "authelia.ingress.traefikCRD.existingTLSOption" .) }}
{{- toYaml .Values.ingress.traefikCRD.tls.existingOptions | nindent 6 }}
{{- else }}
      name: {{ default (include "authelia.name" .) .Values.ingress.traefikCRD.tls.options.nameOverride }}
      namespace: {{ .Release.Namespace }}
{{- end }}
    certResolver: {{ default "default" .Values.ingress.traefikCRD.tls.certResolver }}
    domains:
{{- if .Values.ingress.traefikCRD.tls.domains }}
{{- toYaml .Values.ingress.traefikCRD.tls.domains | nindent 4 }}
{{- else }}
    - main: {{ include "authelia.ingressHost" . }}
{{- end }}
{{- end }}
{{- end -}}